version: "3.8"

services:
  gigachat_db:
    container_name: gigachat_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: GigaChatDb
      POSTGRES_USER: gcAdmin
      POSTGRES_PASSWORD: gcAdminPassword
  gigachat_api:
    container_name: gigachat_api
    build: 
      context: ../src/WebApi
      dockerfile: ./Dockerfile
    environment:
      ConnectionStrings__GigaChatDb: Host=gigachat_db;Port=5432;Database=GigaChatDb;Username=gcAdmin;Password=gcAdminPassword
    depends_on: 
      - gigachat_db
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gigachat_api
